import Input from "@nextui-org/react/esm/input";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState } from "react";
import JSONValue from "../utility/jsonValue";
import SetJsonRoot from "../components/SetJsonRoot";
import json from "../Bloomberg-jobs.json";

const Home: NextPage = () => {
  const [page, setPage] = useState(0);
  const [object, setObject] = useState<JSONValue | undefined>();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/*{(() => {*/}
      {/*  switch (page) {*/}
      {/*    case 0:*/}
      {/*      return (*/}
      {/*        <Input*/}
      {/*          type={"file"}*/}
      {/*          onInput={async (e) => {*/}
      {/*            let text = await (*/}
      {/*              e.target as HTMLInputElement*/}
      {/*            ).files?.[0].text();*/}
      {/*            setObject(JSON.parse(text ?? "{}"));*/}
      {/*            setPage(1);*/}
      {/*          }}*/}
      {/*        />*/}
      {/*      );*/}
      {/*    case 1:*/}
      {/*      return JSON.stringify((object as any).jobData);*/}
      {/*  }*/}
      {/*})()}*/}
      <SetJsonRoot json={json} />
    </div>
  );
};

export default Home;
