import React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useState } from "react";
import JSONValue from "../utility/jsonValue";
import json from "../Bloomberg-jobs.json";
import JSONStructure from "../utility/JSONStructure";

const Parse: React.FC<{ json: JSONValue }> = ({ json }) => {
  let structure = new JSONStructure(json);

  structure.parse();

  return (
    <div style={{ whiteSpace: "pre-wrap" }}>
      {structure
        .recursiveFields()
        .map((o) => o.name)
        .join("\n")}
    </div>
  );
};

const Home: NextPage = () => {
  const [page, setPage] = useState(0);
  const [object, setObject] = useState<JSONValue | undefined>();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Parse json={json} />
    </div>
  );
};

export default Home;
