import type { NextPage } from "next";
import Head from "next/head";
import React from "react";
import FileInput from "../components/FileInput";
import { Button, Card, Container, Link } from "@nextui-org/react";
import DB from "../models/db";
import useLiveQuery from "../utility/hooks/useLiveQuery";

const Home: NextPage = () => {
  const files = useLiveQuery(() => DB.files.toArray());

  return (
    <Container style={{ marginTop: "1em", maxWidth: "800px" }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Card>
        {files
          ? files.map((file) => (
              <Card key={file.id} style={{ marginBottom: "10px" }}>
                <Link href={`/${file.id}/parse`}>
                  <div
                    style={{
                      display: "flex",
                      flexDirection: "row",
                      justifyContent: "space-between",
                      width: "100%",
                    }}
                  >
                    <span>{file.name.split(".json")[0]}</span>
                    <time
                      dateTime={file.uploadedAt.toISOString()}
                      style={{ display: "inline", color: "grey" }}
                    >
                      {file.uploadedAt.toLocaleString()}
                    </time>
                  </div>
                </Link>
              </Card>
            ))
          : "loading files..."}
        <div style={{ display: "flex", gap: "10px" }}>
          <FileInput
            style={{ flex: "1 0 auto" }}
            onFileSelect={async (files) => {
              if (!files) return;
              DB.files.add({
                name: files[0].name,
                uploadedAt: new Date(),
                content: await files[0].text(),
              });
            }}
            clearOnSelect
            accept={".json"}
          />
          <Button
            style={{ flex: "0 1 auto" }}
            onClick={() => {
              DB.files.clear();
            }}
          >
            Clear File List
          </Button>
        </div>
      </Card>
    </Container>
  );
};

export default Home;
