import React, { useEffect } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import JSONValue from "../../utility/jsonValue";
import useLiveQuery from "../../utility/hooks/useLiveQuery";
import { useRouter } from "next/router";
import Application from "../../models/Application";
import { Card, Container, Text } from "@nextui-org/react";

const ParsePage: NextPage = () => {
  const [jsonObject, setJsonObject] = useState<JSONValue>();

  const router = useRouter();
  const { id: idString } = router.query as { id?: string };
  const id = (idString && parseInt(idString)) ?? undefined;

  const application = useLiveQuery(
    () => (id ? Application.fetch(id).then((a) => a ?? null) : undefined),
    [id]
  );

  useEffect(() => {
    (async () => {
      if (!application) return;
      let files = await application.exampleFiles.get();
      let file = [...files][0];
      setJsonObject(JSON.parse(file.content));
    })();
  }, [application]);

  return (
    <Container style={{ marginTop: "1em" }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Card>
        {application ? (
          <div>
            <Text h1>{application.name}</Text>
            <Text h2>Fields</Text>
            {application.baseShape.recursiveFields().map((field) => (
              <Card key={field.name}>
                <div
                  style={{ display: "flex", justifyContent: "space-between" }}
                >
                  {field.name}{" "}
                  <Text span color={"secondary"}>
                    {field.shape.typeName}
                  </Text>
                </div>
              </Card>
            ))}
            {/*{jsonObject ? (*/}
            {/*  <div>{JSON.stringify(jsonObject)}</div>*/}
            {/*) : (*/}
            {/*  "loading..."*/}
            {/*)}*/}
          </div>
        ) : application === undefined ? (
          "loading..."
        ) : (
          "No such application."
        )}
      </Card>
    </Container>
  );
};

export default ParsePage;
